spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: "[dhqclwoa12]"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
